import json

# Dictionary of English to Arabic translations for school management system
translations = {
    "(filtered from _MAX_ total entries)": "(المفلترة من إجمالي _MAX_ مدخل)",
    "...": "...",
    "1. Scan this with your authenticator app": "١. امسح هذا الضوئي باستخدام تطبيق المصادقة الخاص بك",
    "2. Enter the 6-digit code it shows": "٢. أدخل الرمز المكون من ٦ أرقام الظاهر في التطبيق",
    "300×300 Pixels, Max 1 MB (JPG/PNG Only).": "٣٠٠×٣٠٠ بكسل، الحد الأقصى ١ ميجابايت (JPG/PNG فقط).",
    ":count Main + :sidebar Sidebar": ":count رئيسي + :sidebar شريطي",
    "A Class": "صف دراسي",
    "AI Check": "فحص الذكاء الاصطناعي",
    "AI translation creates a new draft revision — review it in History before publishing.": "ينشئ ترجمة بالذكاء الاصطناعي مسودة جديدة — راجعها في السجل قبل النشر.",
    "Absence Alerts": "تنبيهات الغياب",
    "Absent": "غائب",
    "Academic": "أكاديمي",
    "Academic Groups": "المجموعات الأكاديمية",
    "Academic History": "السجل الأكاديمي",
    "Academic Placement": "التسكين الأكاديمي",
    "Academic Year": "العام الدراسي",
    "Academic Year Created.": "تم إنشاء العام الدراسي.",
    "Academic Year Deleted.": "تم حذف العام الدراسي.",
    "Academic Year Pattern": "نمط العام الدراسي",
    "Academic Year Updated.": "تم تحديث العام الدراسي.",
    "Academic Years": "الأعوام الدراسية",
    "Academics": "الشؤون الأكاديمية",
    "Accent": "اللون التمييزي",
    "Accent Color": "اللون التمييزي",
    "Account & Security": "الحساب والأمان",
    "Action": "إجراء",
    "Actions": "الإجراءات",
    "Active": "نشط",
    "Active Staff": "الموظفون النشطون",
    "Active Students": "الطلاب النشطون",
    "Add": "إضافة",
    "Add A Language": "إضافة لغة",
    "Add Assignment": "إضافة واجب",
    "Add Block": "إضافة كتلة",
    "Add Class": "إضافة صف",
    "Add Division": "إضافة قسم",
    "Add Language": "إضافة لغة",
    "Add Lesson": "إضافة درس",
    "Add Rider": "إضافة راكب",
    "Add Subject": "إضافة مادة",
    "Add To Menu": "إضافة للقائمة",
    "Add To Routine": "إضافة للجدول",
    "Add book": "إضافة كتاب",
    "Add driver": "إضافة سائق",
    "Add member": "إضافة عضو",
    "Add new student": "إضافة طالب جديد",
    "Add vehicle": "إضافة مركبة",
    "Additional Information": "معلومات إضافية",
    "Address": "العنوان",
    "Administrator": "مدير النظام",
    "Admission Age": "سن القبول",
    "Admission Date": "تاريخ القبول",
    "Admission Number": "رقم القبول",
    "Admission applications": "طلبات القبول",
    "Admissions": "القبول والتسجيل",
    "Admit Cards": "بطاقات الدخول",
    "Advanced": "متقدم",
    "All": "الكل",
    "All Absent": "الكل غائب",
    "All Active Students": "جميع الطلاب النشطين",
    "All Classes": "جميع الصفوف",
    "All Conversations": "جميع المحادثات",
    "All Present": "الكل حاضر",
    "All Sections": "جميع الشعب",
    "All rights reserved.": "جميع الحقوق محفوظة.",
    "All staff": "جميع الموظفين",
    "All students": "جميع الطلاب",
    "Amount": "المبلغ",
    "Amount Due": "المبلغ المستحق",
    "Announcement Deleted.": "تم حذف الإعلان.",
    "Announcement Published.": "تم نشر الإعلان.",
    "Announcement Updated.": "تم تحديث الإعلان.",
    "Announcements": "الإعلانات",
    "Applicant": "المتقدم",
    "Application Approved — Student Enrolled.": "تمت الموافقة على الطلب — تم تسجيل الطالب.",
    "Application Rejected.": "تم رفض الطلب.",
    "Apply": "تطبيق",
    "Apply Changes": "تطبيق التغييرات",
    "Apply For Admission": "التقديم للقبول",
    "Apply For Leave": "طلب إجازة",
    "Apply Now": "قدّم الآن",
    "Approve": "اعتماد",
    "Approved": "معتمد",
    "Assign": "تعيين",
    "Assignment Created.": "تم إنشاء الواجب.",
    "Assignments": "الواجبات",
    "At A Glance": "لمحة عامة",
    "Attendance": "الحضور والغياب",
    "Attendance History": "سجل الحضور",
    "Attendance Rate": "نسبة الحضور",
    "Attendance Recorded.": "تم تسجيل الحضور.",
    "Attendance Summary": "ملخص الحضور",
    "Attendance Today": "حضور اليوم",
    "Author": "المؤلف",
    "Available": "متاح",
    "Back": "رجوع",
    "Back To Classes": "العودة للصفوف",
    "Back To Course": "العودة للدورة",
    "Back To Courses": "العودة للدورات",
    "Back To Languages": "العودة للغات",
    "Back To Messages": "العودة للرسائل",
    "Back To Students": "العودة للطلاب",
    "Background": "الخلفية",
    "Balance": "الرصيد",
    "Bangla": "البنغالية",
    "Bank Name": "اسم البنك",
    "Bank Transfer": "تحويل بنكي",
    "Basic": "أساسي",
    "Basic Salary": "الراتب الأساسي",
    "Block": "كتلة",
    "Blocked": "محظور",
    "Blocks": "الكتل",
    "Blood Group": "فصيلة الدم",
    "Body": "المحتوى",
    "Book": "كتاب",
    "Book Added.": "تمت إضافة الكتاب.",
    "Book Issued.": "تم إعارة الكتاب.",
    "Book Returned.": "تم إرجاع الكتاب.",
    "Book Updated.": "تم تحديث الكتاب.",
    "Books": "الكتب",
    "Books Issued": "الكتب المعارة",
    "Border": "الحد",
    "Borrow / Return": "إعارة / إرجاع",
    "Borrowed": "معار",
    "Bottom": "أسفل",
    "Boy": "ولد",
    "Browse": "تصفح",
    "Bulk Actions...": "إجراءات جماعية...",
    "Cancel": "إلغاء",
    "Card": "بطاقة",
    "Categories": "التصنيفات",
    "Category": "التصنيف",
    "Change Password": "تغيير كلمة المرور",
    "Check In": "تسجيل دخول",
    "Check Out": "تسجيل خروج",
    "Class": "الصف",
    "Class Routine": "الجدول الدراسي",
    "Class Teacher": "مربّي الصف",
    "Classes": "الصفوف",
    "Clear": "مسح",
    "Click to copy": "انقر للنسخ",
    "Close": "إغلاق",
    "Code": "الرمز",
    "Confirm": "تأكيد",
    "Confirm Password": "تأكيد كلمة المرور",
    "Contact": "اتصال",
    "Contact Us": "اتصل بنا",
    "Course": "الدورة / المقرر",
    "Courses": "المقررات الدراسية",
    "Create": "إنشاء",
    "Create Account": "إنشاء حساب",
    "Created At": "تاريخ الإنشاء",
    "Credit": "رصيد دائن",
    "Current Password": "كلمة المرور الحالية",
    "Dashboard": "لوحة التحكم",
    "Date": "التاريخ",
    "Date of Birth": "تاريخ الميلاد",
    "Days": "الأيام",
    "Deactivate": "إلغاء التفعيل",
    "Default": "الافتراضي",
    "Delete": "حذف",
    "Description": "الوصف",
    "Details": "التفاصيل",
    "Designation": "المسمى الوظيفي",
    "Discount": "خصم",
    "Discounts": "الخصومات",
    "Driver": "السائق",
    "Due Date": "تاريخ الاستحقاق",
    "Edit": "تعديل",
    "Email": "البريد الإلكتروني",
    "Email Address": "عنوان البريد الإلكتروني",
    "Employee": "الموظف",
    "Enable": "تفعيل",
    "Enabled": "مفعل",
    "Enroll": "تسجيل",
    "Enrolled": "مسجل",
    "Enrollment": "التسجيل",
    "Exam": "الامتحان",
    "Exam Hall": "قاعة الامتحان",
    "Exam Halls": "قاعات الامتحانات",
    "Exam Routine": "جدول الامتحانات",
    "Exam Type": "نوع الامتحان",
    "Exams": "الامتحانات",
    "Expense": "المصروفات",
    "Fee Category": "فئة الرسوم",
    "Fee Item": "بند الرسوم",
    "Fees": "الرسوم الدراسية",
    "Female": "أنثى",
    "Filter": "تصفية",
    "First Name": "الاسم الأول",
    "Gender": "الجنس",
    "General Settings": "الإعدادات العامة",
    "Grade": "الدرجة / التقدير",
    "Grade Boundaries": "حدود الدرجات",
    "Grades": "الدرجات",
    "Grading System": "نظام التقييم",
    "Guardian": "ولي الأمر",
    "Guardians": "أولياء الأمور",
    "Hall": "القاعة",
    "Header": "الترويسة",
    "Height": "الارتفاع",
    "Home": "الرئيسية",
    "ID": "المعرف",
    "ID Card": "بطاقة الهوية",
    "ID Cards": "بطاقات الهوية",
    "Income": "الإيرادات",
    "Invoice": "الفاتورة",
    "Invoices": "الفواتير",
    "Language": "اللغة",
    "Languages": "اللغات",
    "Last Name": "اسم العائلة",
    "Late": "متأخر",
    "Leave": "إجازة",
    "Leave Application": "طلب إجازة",
    "Leave Request": "طلب إجازة",
    "Leave Requests": "طلبات الإجازات",
    "Leave Type": "نوع الإجازة",
    "Lesson": "الدرس",
    "Lessons": "الدروس",
    "Librarian": "أمين المكتبة",
    "Library": "المكتبة",
    "Library Books": "كتب المكتبة",
    "Library Member": "عضو المكتبة",
    "List": "قائمة",
    "Loan": "قرض",
    "Loans": "القروض",
    "Location": "الموقع",
    "Lock": "قفل",
    "Login": "تسجيل الدخول",
    "Logout": "تسجيل الخروج",
    "Male": "ذكر",
    "Mark": "الدرجة",
    "Marks": "الدرجات والنتائج",
    "Marks Sheet": "كشف الدرجات",
    "Media": "الوسائط",
    "Member": "عضو",
    "Menu": "القائمة",
    "Menus": "القوائم",
    "Message": "رسالة",
    "Messages": "الرسائل",
    "Messaging": "المراسلات",
    "Mobile": "الجوال",
    "Month": "الشهر",
    "Monthly": "شهري",
    "Name": "الاسم",
    "New": "جديد",
    "Next": "التالي",
    "No": "لا",
    "No records found.": "لم يتم العثور على سجلات.",
    "Notice": "إشعار",
    "Notices": "الإشعارات",
    "Notification": "تنبيه",
    "Notifications": "التنبيهات",
    "Off": "مغلق",
    "On": "مفعل",
    "Online Admission": "القبول الإلكتروني",
    "Open": "مفتوح",
    "Optional": "اختياري",
    "Overview": "نظرة عامة",
    "Paid": "مدفوع",
    "Parent": "ولي الأمر",
    "Parents": "أولياء الأمور",
    "Password": "كلمة المرور",
    "Pay Now": "أدفـع الآن",
    "Payment": "الدفع",
    "Payment Gateway": "بوابة الدفع",
    "Payment History": "سجل المدفوعات",
    "Payment Method": "طريقة الدفع",
    "Payments": "المدفوعات",
    "Payroll": "رواتب الموظفين",
    "Pending": "معلق",
    "Percentage": "النسبة المئوية",
    "Phone": "الهاتف",
    "Phone Number": "رقم الهاتف",
    "Photo": "الصورة",
    "Portal": "البوابة",
    "Position": "المرتبة",
    "Post": "منشور",
    "Present": "حاضر",
    "Previous": "السابق",
    "Print": "طباعة",
    "Profile": "الملف الشخصي",
    "Promote": "ترقية",
    "Publish": "نشر",
    "Published": "منشور",
    "Read": "مقروء",
    "Reason": "السبب",
    "Receipt": "إيصال",
    "Receptionist": "موظف الاستقبال",
    "Recent": "الحديثة",
    "Refund": "استرداد",
    "Rejected": "مرفوض",
    "Remarks": "ملاحظات",
    "Report": "تقرير",
    "Reports": "التقارير",
    "Reset": "إعادة ضبط",
    "Result": "النتيجة",
    "Results": "النتائج",
    "Rider": "راكب",
    "Role": "الدور",
    "Roles": "الأدوار",
    "Room": "الغرفة / القاعة",
    "Route": "المسار",
    "Routes": "المسارات",
    "Routine": "الجدول",
    "SMS": "الرسائل النصية",
    "Salary": "الراتب",
    "Save": "حفظ",
    "Save Changes": "حفظ التغييرات",
    "School": "المدرسة",
    "School Code": "رمز المدرسة",
    "School Info": "معلومات المدرسة",
    "School Name": "اسم المدرسة",
    "School Settings": "إعدادات المدرسة",
    "Search": "بحث",
    "Section": "الشعبة",
    "Sections": "الشعب",
    "Security": "الأمان",
    "Select": "اختر",
    "Send": "إرسال",
    "Send SMS": "إرسال رسالة نصية",
    "Sender": "المرسل",
    "Settings": "الإعدادات",
    "Shift": "الفترة الدراسية",
    "Shifts": "الفترات الدراسية",
    "Site Settings": "إعدادات الموقع",
    "Staff": "الموظفون",
    "Staff Attendance": "حضور الموظفين",
    "Status": "الحالة",
    "Student": "طالب",
    "Student Attendance": "حضور الطلاب",
    "Student ID": "رقم الطالب",
    "Students": "الطلاب",
    "Subject": "المادة",
    "Subjects": "المواد",
    "Submit": "إرسال / تقديم",
    "Success": "نجاح",
    "Super Admin": "المشرف العام",
    "System": "النظام",
    "Teacher": "معلم",
    "Teacher Name": "اسم المعلم",
    "Teachers": "المعلمون",
    "Theme": "المظهر / الثيم",
    "Title": "العنوان",
    "Today": "اليوم",
    "Total": "الإجمالي",
    "Total Students": "إجمالي الطلاب",
    "Total Teachers": "إجمالي المعلمين",
    "Transactions": "المعاملات المالية",
    "Translation": "الترجمة",
    "Translations": "الترجمات",
    "Transport": "النقل المدرسي",
    "Type": "النوع",
    "Unit": "الوحدة",
    "Unpaid": "غير مدفوع",
    "Update": "تحديث",
    "Updated At": "تاريخ التحديث",
    "User": "المستخدم",
    "Users": "المستخدمون",
    "Vehicle": "المركبة",
    "Vehicles": "المركبات",
    "Vendor": "المورد",
    "Version": "الإصدار",
    "View": "عرض",
    "View Details": "عرض التفاصيل",
    "Website": "الموقع الإلكتروني",
    "Weekly": "أسبوعي",
    "Year": "السنة",
    "Yes": "نعم"
}

# Read existing bn.json to keep all key structure
with open(r"d:\projects_test\school larvel\school-management-system\database\seeders\data\translations\bn.json", "r", encoding="utf-8") as f:
    bn_data = json.load(f)

# Read existing ar.json if exists
try:
    with open(r"d:\projects_test\school larvel\school-management-system\database\seeders\data\translations\ar.json", "r", encoding="utf-8") as f:
        ar_data = json.load(f)
except Exception:
    ar_data = {}

# Merge translations
for key in bn_data.keys():
    if key in translations:
        ar_data[key] = translations[key]
    elif key not in ar_data:
        # Fallback: keep key as value if no translation exists yet
        ar_data[key] = key

# Write ar.json
with open(r"d:\projects_test\school larvel\school-management-system\database\seeders\data\translations\ar.json", "w", encoding="utf-8") as f:
    json.dump(ar_data, f, ensure_ascii=False, indent=4)

print(f"Successfully generated ar.json with {len(ar_data)} translation keys.")
